### ISSUE TITLE
Crash: taskqueue element is already linked

### ISSUE THREAD

**Issue by christf** [christf/snapcastc#50]
I just saw this:

> &samplefor'.
> Program terminated with signal SIGABRT, Aborted.
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> 50	../sysdeps/unix/sysv/linux/raise.c: Datei oder Verzeichnis nicht gefunden.
> (gdb) bt
> #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
> #1  0x00007f8e3e655535 in __GI_abort () at abort.c:79
> #2  0x000055dd78fcd715 in _exit_error (status=-1, errnum=0, 
>     format=0x55dd78fd27e0 "taskqueue_link: element already linked")
>     at /home/christof/Programmierung/snapcastc/src/error.h:44
> #3  0x000055dd78fcd87f in exit_bug (
>     format=0x55dd78fd27e0 "taskqueue_link: element already linked")
>     at /home/christof/Programmierung/snapcastc/src/error.h:65
> #4  0x000055dd78fcdd74 in taskqueue_link (queue=0x55dd78fd6348 <snapctx+40>, 
>     elem=0x55dd7af62e60) at /home/christof/Programmierung/snapcastc/src/taskqueue.c:146
> #5  0x000055dd78fce097 in taskqueue_remove (elem=0x55dd7afd4700)
>     at /home/christof/Programmierung/snapcastc/src/taskqueue.c:239
> #6  0x000055dd78fcdcb5 in taskqueue_run (ctx=0x55dd78fd6340 <snapctx+32>)
>     at /home/christof/Programmierung/snapcastc/src/taskqueue.c:131
> #7  0x000055dd78fc6d47 in loop ()
>     at /home/christof/Programmierung/snapcastc/src/server.c:108
> #8  0x000055dd78fc7841 in main (argc=7, argv=0x7ffe48fa0208)
>     at /home/christof/Programmierung/snapcastc/src/server.c:251
> 

I haven't had the chance to have a closer look, posting this for documentation for now.

**Comment by christf** [comment]
this should be fixed by #49
